# Generated by Django 2.1.1 on 2020-03-19 13:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoadMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=200, unique=True, verbose_name='nom du la RoadMap')),
                ('r_durree', models.IntegerField(blank=True, null=True, verbose_name='Duree de chaque sprint en jours')),
                ('r_dateDebut', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SujetTraite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=200, unique=True, verbose_name='intitulé du sujet')),
                ('s_durree', models.IntegerField(default=1, verbose_name='Nombre de sprint du sujet')),
                ('s_ordre', models.IntegerField(default=1, verbose_name='ordre du sujet')),
                ('s_RoadMap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roadmap.RoadMap')),
            ],
        ),
    ]
