# Generated by Django 2.1.1 on 2020-03-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sujettraite',
            name='s_ordre',
        ),
        migrations.AddField(
            model_name='sujettraite',
            name='s_nombreSprint',
            field=models.IntegerField(default=1, verbose_name='nombre de sprint du sujet'),
        ),
        migrations.AddField(
            model_name='sujettraite',
            name='s_sprintDebut',
            field=models.IntegerField(default=1, verbose_name='Sprint de debut du sujet'),
        ),
    ]
