# Generated by Django 2.1.1 on 2020-03-19 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0002_auto_20200319_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sujettraite',
            name='s_nombreSprint',
        ),
    ]
