# Generated by Django 2.1.1 on 2020-03-21 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0003_remove_sujettraite_s_nombresprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='sujettraite',
            name='s_is_utile',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sujettraite',
            name='s_RoadMap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='s_roadMaps', to='roadmap.RoadMap'),
        ),
    ]
